dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

# command to install dependencies
install:
  - pip install .
  - pip install pytest-cov pytest-sugar responses flake8 mypy black isort
# command to run tests

script:
  - isort -c
  - black setup.py src tests --check --verbose
  - mypy setup.py src tests --ignore-missing-imports
  - flake8 setup.py src tests --exit-zero
  - pytest -vv
